spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ywh-shopping-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ywh169747

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
