server:
  port: 8000
  # webflux 不支持
#  servlet:
#    context-path: /shopping
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-web

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 网关本身没有contextPath,通过自己转发自己，达到能处理contextPath
        # 但是会导致不服请求失效
#        - id: self
#          uri: lb://gateway-web
#          predicates:
#            - Path=/${spring.application.name}/**
#          filters:
#            - StripPrefix=1
#          order: -11000

        - id: shopping-service-goods
          uri: lb://service-goods
          predicates:
            - Path=/shopping/service-goods/**
          filters:
            - StripPrefix=1
#            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
#              args:
#                key-resolver: "#{@ipKeyResolver}"
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
        #用户微服务
        - id: shopping-service-order
          uri: lb://service-order
          predicates:
            - Path=/shopping/service-order/**
          filters:
            - StripPrefix=1

        - id: shopping-service-user
          uri: lb://service-user
          predicates:
            - Path=/shopping/service-user/**
          filters:
            - StripPrefix=1

swagger:
  gateway:
    enabled: true

#management:
#  endpoint:
#    gateway:
#      enabled: true
#    web:
#      exposure:
#        include: true